### ISSUE TITLE
Error using package namespace in proto with . in it

### ISSUE THREAD

**Issue by gwihlidal** [konsumer/grpc-dynamic-gateway#3]
I have found an issue where grpc-dynamic-gateway crashes if the package in the proto file contains a . in it (which is helpful for clean code generation in languages like C++)

i.e. this fails:

```
syntax = "proto3";

package test.stuff;

import "google/api/annotations.proto";

service TestService
{
	rpc TestRpc (TestParams) returns (TestData)
	{
		option (google.api.http) =
		{
			post: "/v1/assets/op/execute"
			body: "*"
		};
	}
}

message TestParams
{
	string testField = 1;
}

message TestData
{
	string myData = 1;
}
```

With this error:

```
C:\Users\graham\Documents\Repositories\halcyon>grpc-dynamic-gateway -g 0.0.0.0:50060 -I ./Proto/proto AssetService2.proto
C:\Users\graham\AppData\Roaming\npm\node_modules\grpc-dynamic-gateway\index.js:34
        clients[pkg][svc] = new protos[si][pkg][svc](grpcLocation, credentials)
                                               ^

TypeError: Cannot read property 'TestService' of undefined
    at sch.services.forEach.s (C:\Users\graham\AppData\Roaming\npm\node_modules\grpc-dynamic-gateway\index.js:34:48)
    at Array.forEach (native)
    at protoFiles.map.map.forEach (C:\Users\graham\AppData\Roaming\npm\node_modules\grpc-dynamic-gateway\index.js:32:20)
    at Array.forEach (native)
    at middleware (C:\Users\graham\AppData\Roaming\npm\node_modules\grpc-dynamic-gateway\index.js:29:6)
    at Object.<anonymous> (C:\Users\graham\AppData\Roaming\npm\node_modules\grpc-dynamic-gateway\cli.js:61:26)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

While this:

```
syntax = "proto3";

package teststuff;

import "google/api/annotations.proto";

service TestService
{
	rpc TestRpc (TestParams) returns (TestData)
	{
		option (google.api.http) =
		{
			post: "/v1/assets/op/execute"
			body: "*"
		};
	}
}

message TestParams
{
	string testField = 1;
}

message TestData
{
	string myData = 1;
}
```

Works fine:

```
C:\Users\graham\Documents\Repositories\halcyon>grpc-dynamic-gateway -g 0.0.0.0:50060 -I ./Proto/proto AssetService2.proto
POST /v1/assets/op/execute
Listening on http://0.0.0.0:8080, proxying to gRPC on 0.0.0.0:50060
```

Thank you,
Graham

**Comment by konsumer** [comment]
Hmm, I think this would require recursive namespace resolution. I notice the struct protoc makes looks like this:

```cpp
namespace test {
namespace stuff {
// ... services stuff, here
}  // namespace stuff
}  // namespace test
```

It be a bit of re-work, but it's doable. I'm short on time, right now, but I can look at this, later. In the meantime, feel free to PR, or just use flat (no dot) namespaces.

**Comment by konsumer** [comment]
I think this may also be related to [this](https://github.com/konsumer/grpcnode/issues/2) issue. I am going to take another look.

**Comment by konsumer** [comment]
Closing, as this should be fixed in new versions of grpcnode & grpc-dynamic-gateway.

**Comment by xsorifc28** [comment]
The issue does seem to be solved, however if I **don't** have a [dot] in the package name, it gives an undefined error..

**Comment by xsorifc28** [comment]
Changing the `getPkg` function to this should fix it:

```javascript
const getPkg = (client, pkg, create = false) => {
  if (!((pkg || '').indexOf('.') != -1) && client[pkg] !== undefined) { 
    return client[pkg] 
  }

  if (((pkg || '').indexOf('.') != -1) && client[pkg] !== undefined) { 
    return client[pkg] 
  }
  
  const ls = pkg.split('.')
  let obj = client
  ls.forEach(function (name) {
    if (create) {
      obj[name] = obj[name] || {}
    }
    obj = obj[name]
  })
  console.log("obj is", obj)
  return obj
}

**Comment by WoLfulus** [comment]
When this will be published?
